// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Rokn Shadeed",
    "description": "Rokn Shadeed"
  }
};
export default messages;