// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Rokn Shadeed",
    "description": "Rokn Shadeed"
  },

  "Blog": {
    "close": "Close"
  },

  "Contact": {
    "title": "Contact Us",

    "form": {
      "name": "Name",
      "email": "Email",
      "phone": "Phone",
      "message": "Message",
      "button": "Send"
    },

    "messages": {
      "success": {
        "title": "Message Sent Successfully",
        "description": "Thank you for contacting us. We will get back to you as soon as possible."
      },
      "error": {
        "title": "Sending Failed",
        "description": "An error occurred while sending the message. Please try again."
      }
    }
  },

  "Footer": {
    "button": "Report a Product",
    "title": {
      "item-1": "This guide is powered by a global community",
      "item-2": "Share your knowledge and make a difference"
    },
    "description": {
      "item-1": "Help us keep the list accurate and up-to-date",
      "item-2": "Together, our choices make an impact"
    }
  }
};
export default messages;